# Generated by Django 4.2.1 on 2023-05-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='question1',
            new_name='Q1',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='question2',
            new_name='Q2',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='question3',
            new_name='Q3',
        ),
    ]
